---
- name: Set up Monica on a given EC2 instance
  hosts: webserver
  tasks:
  - yum:
      name: vim
      state: latest
  - yum:
      name: "*"
      state: latest
    become: yes

  - name: Download docker-compose
    become: true
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Add epel repo
    become: yes
    yum:
      name: epel-release
      state: present

  - name: Install docker
    become: yes
    yum:
      name: docker
      state: present
